### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by kisonay** [crscheid/pocketmine-mp#1]
Were do the plugin data persist? I created a plugins folder but anything in it isn't active.

**Comment by crscheid** [comment]
Hey there. So I don't persist the plugins external to the container, but you could do that easily by modifying the Dockerfile definition and mapping the plugins folder. If you feel up to it, please submit a pull request. Otherwise, I can add this to the next revision.

In the meantime, if you are using docker, then you can use the following command after your container is running:

`docker exec -ti minecraft bash`

Note: This assumes your container is called "minecraft".

Then you can navigate to the plugins folder and manage them from there.

**Comment by kisonay** [comment]
I’ll submit a pull request tomorrow. Will add plugins, resource-packs and server.log if that is ok.

**Comment by crscheid** [comment]
Sounds great. Looked at your fork briefly and looks like you made some great changes! Thanks!

**Comment by kisonay** [comment]
Thanks for merging that, the latest works well.

**Comment by crscheid** [comment]
No problem. By the way, the docker image should be auto-built as well. https://hub.docker.com/r/cscheide/pocketmine-mp/
