### ISSUE TITLE
Setting config values on launch

### ISSUE THREAD

**Issue by pogzie** [crscheid/pocketmine-mp#7]
Is there any way to do this? Like env variables in the docker command?

**Comment by crscheid** [comment]
There is not a way to do so on a config-value by config-value basis at present. It could get quite tricky as well. 

The container _could_ conceivably read the environment and replace certain values in the configuration files at runtime, but since PMMP expects this information to be only available in the configuration files, this would overwrite the configuration file maintained either within the container or mapped via a volume.

Just curious why you would want to do this vs just passing in a configuration file that contains all of your configuration. You could just pass in a reference to the config file directly instead of mapping a whole directory.

```
docker run -d -v /your-server.properties:/data/server.properties -p 19132:19132/udp --name minecraft cscheide/pocketmine-mp:latest
```

I'll leave this open for discussion.

**Comment by pogzie** [comment]
I am actually running this on DC/OS (https://dcos.io/) and was able to set it up in 5 minutes. 

Im still playing around with this but my first agenda is the customization of the `server.properties` file. I will try your approach and possibly just run `start.sh` via a CMD and do some pre-configuration before that. Or probably just use artifacts containing my config and pre-load that before starting. 

Thanks for the insight though!

**Comment by crscheid** [comment]
Very cool that you're running this on DC/OS. 

Regarding starting, that's exactly what I do. I just wrap it in a start.sh script like this:

```sh
#!/bin/bash
docker pull cscheide/pocketmine-mp:3.1
docker run -d -ti -p 19132:19132/udp -v /path/to/data:/data --name minecraft cscheide/pocketmine-mp:3.1
```
